title: Yonghyeon Lee
url: "https://gabe-yhlee.github.io/"
logo: /assets/img/YHLee.jpg
description: PhD Student in Robotics laboratory at the Seoul National University 
theme: jekyll-theme-minimal
search : true